### ISSUE TITLE
Should We Create another way to communicate ?

### ISSUE THREAD

**Issue by Werner1201** [Werner1201/weather_tray-rs#6]
@nicolasbauw I've been talking to you via the pull requests and sometimes it makes me think I'm using it wrong. Should we use another way, like discord or something like that ? just a chat so we can express with more responsiviness

**Comment by nicolasbauw** [comment]
Good idea, my discord ID: HM_Kaiser
Please note that I'm currently on summer holiday, I'm not *always* on the computer ;-)

**Comment by Werner1201** [comment]
Alright I'll add you there do you have the #number after your name there ? @nicolasbauw

**Comment by Werner1201** [comment]
Because there's a code of 4 digits that makes your account unique

**Comment by Werner1201** [comment]
![image](https://user-images.githubusercontent.com/8631657/90634813-b1d9b880-e1fe-11ea-8794-c61709bb6845.png)

**Comment by Werner1201** [comment]
heres mine nickname: WernerVonRomling#6795

**Comment by nicolasbauw** [comment]
It's HM_Kaiser#7464, I've made a request on discord
